// registry.typ — Datengetriebene Block-Registry (Vollständig)
// Enthält alle Scratch-Blöcke mit offiziellen Bezeichnungen

#let REGISTRY = (
  // =====================
  // EREIGNISSE (Events)
  // =====================
  "event.when_flag_clicked": (
    de: "Wenn {flag} angeklickt wird",
    en: "when {flag} clicked",
    fr: "quand {flag} est cliqué",
    shape: "hat",
    category: "ereignisse",
  ),
  "event.when_key_pressed": (
    de: "Wenn Taste {key} gedrückt wird",
    en: "when {key} key pressed",
    fr: "quand la touche {key} est pressée",
    shape: "hat",
    category: "ereignisse",
  ),
  "event.when_sprite_clicked": (
    de: "Wenn diese Figur angeklickt wird",
    en: "when this sprite clicked",
    fr: "quand ce sprite est cliqué",
    shape: "hat",
    category: "ereignisse",
  ),
  "event.when_scene_starts": (
    de: "Wenn Bühnenbild zu {scene} wechselt",
    en: "when backdrop switches to {scene}",
    fr: "quand l'arrière-plan bascule sur {scene}",
    shape: "hat",
    category: "ereignisse",
  ),
  "event.when_value_exceeds": (
    de: "Wenn {element} > {value}",
    en: "when {element} > {value}",
    fr: "quand le {element} > {value}",
    shape: "hat",
    category: "ereignisse",
  ),
  "event.when_message_received": (
    de: "Wenn ich {message1} empfange",
    en: "when I receive {message1}",
    fr: "quand je reçois {message1}",
    shape: "hat",
    category: "ereignisse",
  ),
  "event.broadcast": (
    de: "sende {message2} an alle",
    en: "broadcast {message2}",
    fr: "envoyer à tous {message2}",
    shape: "stack",
    category: "ereignisse",
  ),
  "event.broadcast_and_wait": (
    de: "sende {message2} an alle und warte",
    en: "broadcast {message2} and wait",
    fr: "envoyer à tous {message2} et attendre",
    shape: "stack",
    category: "ereignisse",
  ),

  // =====================
  // BEWEGUNG (Motion)
  // =====================
  "motion.move_steps": (
    de: "gehe {steps} er Schritt",
    en: "move {steps} steps",
    fr: "avancer de {steps} pas",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.turn_right": (
    de: "drehe dich {arrow-right} um {degrees} Grad",
    en: "turn {arrow-right} {degrees} degrees",
    fr: "tourner {arrow-right} de {degrees} degrés",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.turn_left": (
    de: "drehe dich {arrow-left} um {degrees} Grad",
    en: "turn {arrow-left} {degrees} degrees",
    fr: "tourner {arrow-left} de {degrees} degrés",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.goto": (
    de: "gehe zu {to}",
    en: "go to {to}",
    fr: "aller à {to}",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.goto_xy": (
    de: "gehe zu x: {x} y: {y}",
    en: "go to x: {x} y: {y}",
    fr: "aller à x: {x} y: {y}",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.glide": (
    de: "gleite {secs} Sek. zu {to}",
    en: "glide {secs} secs to {to}",
    fr: "glisser en {secs} secondes à {to}",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.glide_to_xy": (
    de: "gleite {secs} Sek. zu x: {x} y: {y}",
    en: "glide {secs} secs to x: {x} y: {y}",
    fr: "glisser en {secs} secondes à x: {x} y: {y}",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.point_in_direction": (
    de: "setze Richtung auf {direction} Grad",
    en: "point in direction {direction}",
    fr: "s'orienter à {direction}",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.point_towards": (
    de: "drehe dich zu {towards}",
    en: "point towards {towards}",
    fr: "s'orienter vers {towards}",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.change_x": (
    de: "ändere x um {dx}",
    en: "change x by {dx}",
    fr: "ajouter {dx} à x",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.set_x": (
    de: "setze x auf {x}",
    en: "set x to {x}",
    fr: "mettre x à {x}",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.change_y": (
    de: "ändere y um {dy}",
    en: "change y by {dy}",
    fr: "ajouter {dy} à y",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.set_y": (
    de: "setze y auf {y}",
    en: "set y to {y}",
    fr: "mettre y à {y}",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.if_on_edge_bounce": (
    de: "pralle vom Rand ab",
    en: "if on edge, bounce",
    fr: "rebondir si le bord est atteint",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.set_rotation_style": (
    de: "setze Drehtyp auf {style}",
    en: "set rotation style {style}",
    fr: "fixer le sens de rotation {style}",
    shape: "stack",
    category: "bewegung",
  ),
  "motion.x_position": (
    de: "x-Position",
    en: "x position",
    fr: "abscisse x",
    shape: "reporter",
    category: "bewegung",
  ),
  "motion.y_position": (
    de: "y-Position",
    en: "y position",
    fr: "ordonnée y",
    shape: "reporter",
    category: "bewegung",
  ),
  "motion.direction": (
    de: "Richtung",
    en: "direction",
    fr: "direction",
    shape: "reporter",
    category: "bewegung",
  ),

  // =====================
  // AUSSEHEN (Looks)
  // =====================
  "looks.say_for_secs": (
    de: "sage {message} für {secs} Sekunden",
    en: "say {message} for {secs} seconds",
    fr: "dire {message} pendant {secs} secondes",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.say": (
    de: "sage {message}",
    en: "say {message}",
    fr: "dire {message}",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.think_for_secs": (
    de: "denke {message} für {secs} Sekunden",
    en: "think {message} for {secs} seconds",
    fr: "penser à {message} pendant {secs} secondes",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.think": (
    de: "denke {message}",
    en: "think {message}",
    fr: "penser à {message}",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.switch_costume_to": (
    de: "wechsle zu Kostüm {costume}",
    en: "switch costume to {costume}",
    fr: "basculer sur le costume {costume}",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.next_costume": (
    de: "nächstes Kostüm",
    en: "next costume",
    fr: "costume suivant",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.switch_backdrop_to": (
    de: "wechsle zu Bühnenbild {backdrop}",
    en: "switch backdrop to {backdrop}",
    fr: "basculer sur l'arrière-plan {backdrop}",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.next_backdrop": (
    de: "nächstes Bühnenbild",
    en: "next backdrop",
    fr: "arrière-plan suivant",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.change_size_by": (
    de: "ändere Größe um {change}",
    en: "change size by {change}",
    fr: "ajouter {change} à la taille",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.set_size_to": (
    de: "setze Größe auf {size} %",
    en: "set size to {size} %",
    fr: "mettre la taille à {size} % de la taille initiale",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.change_effect_by": (
    de: "ändere Effekt {effect} um {change}",
    en: "change {effect} effect by {change}",
    fr: "ajouter {change} à l'effet {effect}",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.set_effect_to": (
    de: "setze Effekt {effect} auf {value}",
    en: "set {effect} effect to {value}",
    fr: "mettre l'effet {effect} à {value}",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.clear_graphic_effects": (
    de: "schalte Grafikeffekte aus",
    en: "clear graphic effects",
    fr: "annuler les effets graphiques",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.show": (
    de: "zeige dich",
    en: "show",
    fr: "montrer",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.hide": (
    de: "verstecke dich",
    en: "hide",
    fr: "cacher",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.goto_front_back": (
    de: "gehe zu {layer} Ebene",
    en: "go to {layer} layer",
    fr: "aller à l'{layer} plan",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.go_forward_backward_layers": (
    de: "gehe {num} Ebenen nach {direction}",
    en: "go {direction} {num} layers",
    fr: "déplacer de {num} plans vers l'{direction}",
    shape: "stack",
    category: "aussehen",
  ),
  "looks.costume_number_name": (
    de: "Kostüm {property}",
    en: "costume {property}",
    fr: "{property} du costume",
    shape: "reporter",
    category: "aussehen",
  ),
  "looks.backdrop_number_name": (
    de: "Bühnenbild {property}",
    en: "backdrop {property}",
    fr: "{property} de l'arrière-plan",
    shape: "reporter",
    category: "aussehen",
  ),
  "looks.size": (
    de: "Größe",
    en: "size",
    fr: "taille",
    shape: "reporter",
    category: "aussehen",
  ),

  // =====================
  // KLANG (Sound)
  // =====================
  "sound.play_until_done": (
    de: "spiele Klang {sound} ganz",
    en: "play sound {sound} until done",
    fr: "jouer le son {sound} jusqu'au bout",
    shape: "stack",
    category: "klang",
  ),
  "sound.start_sound": (
    de: "spiele Klang {sound}",
    en: "start sound {sound}",
    fr: "jouer le son {sound}",
    shape: "stack",
    category: "klang",
  ),
  "sound.stop_all_sounds": (
    de: "stoppe alle Klänge",
    en: "stop all sounds",
    fr: "arrêter tous les sons",
    shape: "stack",
    category: "klang",
  ),
  "sound.change_effect_by": (
    de: "ändere {effect}-Effekt um {value}",
    en: "change {effect} effect by {value}",
    fr: "ajouter {value} à l'effet {effect}",
    shape: "stack",
    category: "klang",
  ),
  "sound.set_effect_to": (
    de: "setze {effect}-Effekt auf {value}",
    en: "set {effect} effect to {value}",
    fr: "mettre l'effet {effect} à {value}",
    shape: "stack",
    category: "klang",
  ),
  "sound.clear_effects": (
    de: "schalte Klangeffekte aus",
    en: "clear sound effects",
    fr: "annuler tous les effets sonores",
    shape: "stack",
    category: "klang",
  ),
  "sound.change_volume_by": (
    de: "ändere Lautstärke um {volume}",
    en: "change volume by {volume}",
    fr: "ajouter {volume} au volume",
    shape: "stack",
    category: "klang",
  ),
  "sound.set_volume_to": (
    de: "setze Lautstärke auf {volume} %",
    en: "set volume to {volume} %",
    fr: "mettre le volume à {volume} %",
    shape: "stack",
    category: "klang",
  ),
  "sound.volume": (
    de: "Lautstärke",
    en: "volume",
    fr: "volume",
    shape: "reporter",
    category: "klang",
  ),

  // =====================
  // STEUERUNG (Control)
  // =====================
  "control.wait": (
    de: "warte {duration} Sekunden",
    en: "wait {duration} seconds",
    fr: "attendre {duration} secondes",
    shape: "stack",
    category: "steuerung",
  ),
  "control.repeat": (
    de: "wiederhole {times} mal",
    en: "repeat {times} times",
    fr: "répéter {times} fois",
    shape: "c-block",
    category: "steuerung",
  ),
  "control.forever": (
    de: "wiederhole fortlaufend",
    en: "forever",
    fr: "répéter indéfiniment",
    shape: "cap",
    category: "steuerung",
  ),
  "control.if": (
    de: "falls {condition}",
    en: "if {condition} then",
    fr: "si {condition} alors",
    shape: "c-block",
    category: "steuerung",
  ),
  "control.if_else": (
    de: "falls {condition}, sonst",
    en: "if {condition} then, else",
    fr: "si {condition} alors, sinon",
    shape: "c-block",
    category: "steuerung",
  ),
  "control.wait_until": (
    de: "warte bis {condition}",
    en: "wait until {condition}",
    fr: "attendre jusqu'à ce que {condition}",
    shape: "stack",
    category: "steuerung",
  ),
  "control.repeat_until": (
    de: "wiederhole bis {condition}",
    en: "repeat until {condition}",
    fr: "répéter jusqu'à ce que {condition}",
    shape: "c-block",
    category: "steuerung",
  ),
  "control.stop": (
    de: "stoppe {option}",
    en: "stop {option}",
    fr: "stop {option}",
    shape: "cap",
    category: "steuerung",
  ),
  "control.start_as_clone": (
    de: "Wenn ich als Klon entstehe",
    en: "when I start as a clone",
    fr: "quand je commence comme un clone",
    shape: "hat",
    category: "steuerung",
  ),
  "control.create_clone_of": (
    de: "erzeuge Klon von {clone}",
    en: "create clone of {clone}",
    fr: "créer un clone de {clone}",
    shape: "stack",
    category: "steuerung",
  ),
  "control.delete_this_clone": (
    de: "lösche diesen Klon",
    en: "delete this clone",
    fr: "supprimer ce clone",
    shape: "cap",
    category: "steuerung",
  ),

  // =====================
  // FÜHLEN (Sensing)
  // =====================
  "sensing.touching_object": (
    de: "wird {object} berührt?",
    en: "touching {object} ?",
    fr: "touche le {object} ?",
    shape: "boolean",
    category: "fühlen",
  ),
  "sensing.touching_color": (
    de: "wird Farbe {color} berührt?",
    en: "touching color {color} ?",
    fr: "couleur {color} touchée ?",
    shape: "boolean",
    category: "fühlen",
  ),
  "sensing.color_is_touching_color": (
    de: "Farbe {color1} berührt {color2} ?",
    en: "color {color1} is touching {color2} ?",
    fr: "couleur {color1} touche {color2} ?",
    shape: "boolean",
    category: "fühlen",
  ),
  "sensing.distance_to": (
    de: "Entfernung von {object}",
    en: "distance to {object}",
    fr: "distance de {object}",
    shape: "reporter",
    category: "fühlen",
  ),
  "sensing.ask_and_wait": (
    de: "frage {question} und warte",
    en: "ask {question} and wait",
    fr: "demander {question} et attendre",
    shape: "stack",
    category: "fühlen",
  ),
  "sensing.answer": (
    de: "Antwort",
    en: "answer",
    fr: "réponse",
    shape: "reporter",
    category: "fühlen",
  ),
  "sensing.key_pressed": (
    de: "Taste {key2} gedrückt?",
    en: "key {key2} pressed?",
    fr: "touche {key2} pressée ?",
    shape: "boolean",
    category: "fühlen",
  ),
  "sensing.mouse_down": (
    de: "Maustaste gedrückt?",
    en: "mouse down?",
    fr: "souris pressée ?",
    shape: "boolean",
    category: "fühlen",
  ),
  "sensing.mouse_x": (
    de: "Maus x-Position",
    en: "mouse x",
    fr: "souris x",
    shape: "reporter",
    category: "fühlen",
  ),
  "sensing.mouse_y": (
    de: "Maus y-Position",
    en: "mouse y",
    fr: "souris y",
    shape: "reporter",
    category: "fühlen",
  ),
  "sensing.set_drag_mode": (
    de: "setze Ziehbarkeit auf {mode}",
    en: "set drag mode {mode}",
    fr: "mettre mode de glissement à {mode}",
    shape: "stack",
    category: "fühlen",
  ),
  "sensing.loudness": (
    de: "Lautstärke",
    en: "loudness",
    fr: "volume sonore",
    shape: "reporter",
    category: "fühlen",
  ),
  "sensing.timer": (
    de: "Stoppuhr",
    en: "timer",
    fr: "chronomètre",
    shape: "reporter",
    category: "fühlen",
  ),
  "sensing.reset_timer": (
    de: "setze Stoppuhr zurück",
    en: "reset timer",
    fr: "réinitialiser le chronomètre",
    shape: "stack",
    category: "fühlen",
  ),
  "sensing.of": (
    de: "{property} von {object}",
    en: "{property} of {object}",
    fr: "{property} de {object}",
    shape: "reporter",
    category: "fühlen",
  ),
  "sensing.current": (
    de: "aktuell {timeunit}",
    en: "current {timeunit}",
    fr: "{timeunit} actuelle",
    shape: "reporter",
    category: "fühlen",
  ),
  "sensing.days_since_2000": (
    de: "Tage seit 2000",
    en: "days since 2000",
    fr: "jours depuis 2000",
    shape: "reporter",
    category: "fühlen",
  ),
  "sensing.username": (
    de: "Benutzername",
    en: "username",
    fr: "nom d'utilisateur",
    shape: "reporter",
    category: "fühlen",
  ),

  // =====================
  // OPERATOREN (Operators)
  // =====================
  "operator.add": (
    de: "{num1} + {num2}",
    en: "{num1} + {num2}",
    fr: "{num1} + {num2}",
    shape: "reporter",
    category: "operatoren",
  ),
  "operator.subtract": (
    de: "{num1} - {num2}",
    en: "{num1} - {num2}",
    fr: "{num1} - {num2}",
    shape: "reporter",
    category: "operatoren",
  ),
  "operator.multiply": (
    de: "{num1} * {num2}",
    en: "{num1} * {num2}",
    fr: "{num1} * {num2}",
    shape: "reporter",
    category: "operatoren",
  ),
  "operator.divide": (
    de: "{num1} / {num2}",
    en: "{num1} / {num2}",
    fr: "{num1} / {num2}",
    shape: "reporter",
    category: "operatoren",
  ),
  "operator.random": (
    de: "Zufallszahl von {from} bis {to2}",
    en: "pick random {from} to {to2}",
    fr: "nombre aléatoire entre {from} et {to2}",
    shape: "reporter",
    category: "operatoren",
  ),
  "operator.gt": (
    de: "{operand1} > {operand2}",
    en: "{operand1} > {operand2}",
    fr: "{operand1} > {operand2}",
    shape: "boolean",
    category: "operatoren",
  ),
  "operator.lt": (
    de: "{operand1} < {operand2}",
    en: "{operand1} < {operand2}",
    fr: "{operand1} < {operand2}",
    shape: "boolean",
    category: "operatoren",
  ),
  "operator.equals": (
    de: "{operand1} = {operand2}",
    en: "{operand1} = {operand2}",
    fr: "{operand1} = {operand2}",
    shape: "boolean",
    category: "operatoren",
  ),
  "operator.and": (
    de: "{operand1} und {operand2}",
    en: "{operand1} and {operand2}",
    fr: "{operand1} et {operand2}",
    shape: "boolean",
    category: "operatoren",
  ),
  "operator.or": (
    de: "{operand1} oder {operand2}",
    en: "{operand1} or {operand2}",
    fr: "{operand1} ou {operand2}",
    shape: "boolean",
    category: "operatoren",
  ),
  "operator.not": (
    de: "nicht {operand}",
    en: "not {operand}",
    fr: "non {operand}",
    shape: "boolean",
    category: "operatoren",
  ),
  "operator.join": (
    de: "verbinde {string1} und {string2}",
    en: "join {string1} {string2}",
    fr: "regrouper {string1} et {string2}",
    shape: "reporter",
    category: "operatoren",
  ),
  "operator.letter_of": (
    de: "Zeichen {letter} von {string}",
    en: "letter {letter} of {string}",
    fr: "lettre {letter} de {string}",
    shape: "reporter",
    category: "operatoren",
  ),
  "operator.length": (
    de: "Länge von {string}",
    en: "length of {string}",
    fr: "longueur de {string}",
    shape: "reporter",
    category: "operatoren",
  ),
  "operator.contains": (
    de: "{string1} enthält {string2} ?",
    en: "{string1} contains {string2} ?",
    fr: "{string1} contient {string2} ?",
    shape: "boolean",
    category: "operatoren",
  ),
  "operator.mod": (
    de: "{num1} mod {num2}",
    en: "{num1} mod {num2}",
    fr: "{num1} modulo {num2}",
    shape: "reporter",
    category: "operatoren",
  ),
  "operator.round": (
    de: "runde {num}",
    en: "round {num}",
    fr: "arrondi de {num}",
    shape: "reporter",
    category: "operatoren",
  ),
  "operator.mathop": (
    de: "{operator} von {num}",
    en: "{operator} of {num}",
    fr: "{operator} de {num}",
    shape: "reporter",
    category: "operatoren",
  ),

  // =====================
  // VARIABLEN (Variables)
  // =====================
  "data.set_variable_to": (
    de: "setze {variable} auf {value}",
    en: "set {variable} to {value}",
    fr: "mettre {variable} à {value}",
    shape: "stack",
    category: "variablen",
  ),
  "data.change_variable_by": (
    de: "ändere {variable} um {value}",
    en: "change {variable} by {value}",
    fr: "ajouter {value} à {variable}",
    shape: "stack",
    category: "variablen",
  ),
  "data.show_variable": (
    de: "zeige Variable {variable}",
    en: "show variable {variable}",
    fr: "montrer la variable {variable}",
    shape: "stack",
    category: "variablen",
  ),
  "data.hide_variable": (
    de: "verstecke Variable {variable}",
    en: "hide variable {variable}",
    fr: "cacher la variable {variable}",
    shape: "stack",
    category: "variablen",
  ),

  // =====================
  // LISTEN (Lists)
  // =====================
  "data.add_to_list": (
    de: "füge {item} zu {list} hinzu",
    en: "add {item} to {list}",
    fr: "ajouter {item} à {list}",
    shape: "stack",
    category: "listen",
  ),
  "data.delete_of_list": (
    de: "entferne {index} aus {list}",
    en: "delete {index} of {list}",
    fr: "supprimer l'élement {index} de {list}",
    shape: "stack",
    category: "listen",
  ),
  "data.delete_all_of_list": (
    de: "entferne alles aus {list}",
    en: "delete all of {list}",
    fr: "supprimer tous les éléments de {list}",
    shape: "stack",
    category: "listen",
  ),
  "data.insert_at_list": (
    de: "füge {item} bei {index} in {list} ein",
    en: "insert {item} at {index} of {list}",
    fr: "insérer {item} en position {index} de {list}",
    shape: "stack",
    category: "listen",
  ),
  "data.replace_item_of_list": (
    de: "ersetze Element {index} von {list} durch {item}",
    en: "replace item {index} of {list} with {item}",
    fr: "remplacer l'élément {index} de {list} par {item}",
    shape: "stack",
    category: "listen",
  ),
  "data.item_of_list": (
    de: "Element {index} von {list}",
    en: "item {index} of {list}",
    fr: "élément {index} de {list}",
    shape: "reporter",
    category: "listen",
  ),
  "data.item_number_of_list": (
    de: "Nummer von {item} in {list}",
    en: "item # of {item} in {list}",
    fr: "position de {item} dans {list}",
    shape: "reporter",
    category: "listen",
  ),
  "data.length_of_list": (
    de: "Länge von {list}",
    en: "length of {list}",
    fr: "longueur de {list}",
    shape: "reporter",
    category: "listen",
  ),
  "data.list_contains_item": (
    de: "{list} enthält {item} ?",
    en: "{list} contains {item} ?",
    fr: "{list} contient {item} ?",
    shape: "boolean",
    category: "listen",
  ),
  "data.show_list": (
    de: "zeige Liste {list}",
    en: "show list {list}",
    fr: "montrer la liste {list}",
    shape: "stack",
    category: "listen",
  ),
  "data.hide_list": (
    de: "verstecke Liste {list}",
    en: "hide list {list}",
    fr: "cacher la liste {list}",
    shape: "stack",
    category: "listen",
  ),
  // =====================
  // malstift (Pen)
  // =====================
  "pen.erase_all": (
    de: "{pen} lösche alles",
    en: "{pen} erase all",
    fr: "{pen} effacer tout",
    shape: "stack",
    category: "malstift",
  ),
  "pen.stamp": (
    de: "{pen} hinterlasse Abdruck",
    en: "{pen} stamp",
    fr: "{pen} estampiller",
    shape: "stack",
    category: "malstift",
  ),
  "pen.down": (
    de: "{pen} schalte Stift ein",
    en: "{pen} pen down",
    fr: "{pen} stylo en position d'écriture",
    shape: "stack",
    category: "malstift",
  ),
  "pen.up": (
    de: "{pen} schalte Stift aus",
    en: "{pen} pen up",
    fr: "{pen} relever le stylo",
    shape: "stack",
    category: "malstift",
  ),
  "pen.set_color": (
    de: "{pen} setze Stiftfarbe auf {color}",
    en: "{pen} set pen color to {color}",
    fr: "{pen} mettre la couleur du stylo à {color}",
    shape: "stack",
    category: "malstift",
  ),
  "pen.change_component_by": (
    de: "{pen} ändere Stift {component} um {value}",
    en: "{pen} change pen {component} by {value}",
    fr: "{pen} ajouter {value} à la {component} du stylo",
    shape: "stack",
    category: "malstift",
  ),
  "pen.set_component": (
    de: "{pen} setze Stift {component} auf {value}",
    en: "{pen} set pen {component} to {value}",
    fr: "{pen} mettre la {component} du stylo à {value}",
    shape: "stack",
    category: "malstift",
  ),
  "pen.change_size_by": (
    de: "{pen} ändere Stiftdicke um {value}",
    en: "{pen} change pen size by {value}",
    fr: "{pen} ajouter {value} à la taille du stylo",
    shape: "stack",
    category: "malstift",
  ),
  "pen.set_size_to": (
    de: "{pen} setze Stiftdicke auf {value}",
    en: "{pen} set pen size to {value}",
    fr: "{pen} mettre la taille du stylo à {value}",
    shape: "stack",
    category: "malstift",
  ),
  

  // =====================
  // EIGENE BLÖCKE (Custom Blocks)
  // =====================
  "custom.input": (
    de: "{text}",
    en: "{text}",
    fr: "{text}",
    shape: "input",
    category: "eigene",
  ),
  "custom.block": (
    de: "{label}",
    en: "{label}",
    fr: "{label}",
    shape: "stack",
    category: "eigene",
  ),
  "custom.define": (
    de: "Definiere {label}",
    en: "define {label}",
    fr: "définir {label}",
    shape: "define",
    category: "eigene",
  ),
)
