[package]
name = "blockst"
version = "0.4.0"
entrypoint = "package.typ"
authors = ["Loewe1000 <@Loewe1000>"]
repository = "https://github.com/Loewe1000/blockst"
keywords = ["scratch", "blockly", "jwinf", "open-roberta", "education", "programming", "blocks"]
categories = ["visualization", "components", "languages"]
disciplines = ["education", "computer-science"]
compiler = "0.15.0"
exclude = [
	".DS_Store",
	"*.pdf",
	"/examples",
	"/docs",
]

description = "Render Scratch, Blockly and Open Roberta blocks for educational documents."
license = "MIT"
